# Generated by Django 5.2.12 on 2026-03-30 06:44

import django.db.models.deletion
import sessions_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=sessions_app.models.generate_session_token, help_text='Secure token for client to join this session', max_length=128, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for client'), ('active', 'Active'), ('ended', 'Ended')], db_index=True, default='waiting', max_length=10)),
                ('client_connected', models.BooleanField(default=False)),
                ('agent_connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=sessions_app.models.default_expiry)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Session',
                'verbose_name_plural': 'Support Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
