# Generated by Django 5.2.12 on 2026-04-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_supportsession_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsession',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supportsession',
            name='machine_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique hardware-bound ID from the client machine', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supportsession',
            name='os_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
